


POST http://localhost:8000/api/user/auth/login
Content-Type: application/json 

{
    "email":"mohamedeshiba2021@gmail.com",
    "password":"12345"
}
### 
GET http://localhost:8000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRlc2hpYmEyMDIxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDUiLCJpYXQiOjE2Mzg0NjQ0NTcsImV4cCI6MTYzODQ2NDUxN30.u7F6T4T_j7xVdDsV5LEzHD312DBkYsk_NieQZlowLE8
### 
POST http://localhost:8000/api/user/auth/refreshToken
Content-Type: application/json 

{

    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRlc2hpYmEyMDIxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDUiLCJpYXQiOjE2Mzg0NjQ0MjR9.0U9FY-BQ8pIQMN3fNZcOHt3TMLtVovXqGZPTHyn5fjM"
}
###
DELETE  http://localhost:8000/api/user/auth/logout
Content-Type: application/json 

{

 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRlc2hpYmEyMDIxQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDUiLCJpYXQiOjE2Mzg0NjQ0MjR9.0U9FY-BQ8pIQMN3fNZcOHt3TMLtVovXqGZPTHyn5fjM"

}

